// <auto-generated />
using System;
using CementoTrazabilidad.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CementoTrazabilidad.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203204122_FixPendingChanges")]
    partial class FixPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ConsumoBolsas", b =>
                {
                    b.Property<int>("ConsumoBolsasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumoBolsasID"));

                    b.Property<int>("BolsasDefectuosas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadBolsas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsumo")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoteBolsa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProduccionMaterialID")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorBolsaID")
                        .HasColumnType("int");

                    b.Property<string>("TipoCemento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("ConsumoBolsasID");

                    b.HasIndex("ProduccionMaterialID");

                    b.HasIndex("ProveedorBolsaID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("ConsumoBolsas", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Despacho", b =>
                {
                    b.Property<int>("DespachoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DespachoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespachoID"));

                    b.Property<int?>("Bolsas")
                        .HasColumnType("int")
                        .HasColumnName("Bolsas");

                    b.Property<int?>("Camiones")
                        .HasColumnType("int")
                        .HasColumnName("Camiones");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Destino");

                    b.Property<DateTime?>("FechaHoraDespacho")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHoraDespacho");

                    b.Property<int?>("MaterialID")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Modalidad");

                    b.Property<decimal?>("Toneladas")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Toneladas");

                    b.Property<int?>("TurnoProduccionID")
                        .HasColumnType("int")
                        .HasColumnName("TurnoProduccionID");

                    b.HasKey("DespachoID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("Despacho", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.EventoCarga", b =>
                {
                    b.Property<int>("EventoCargaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoCargaID"));

                    b.Property<int?>("CantidadBolsas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.Property<string>("ZonaCarga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EventoCargaID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("EventosCarga", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.LoteProduccion", b =>
                {
                    b.Property<int>("LoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteID"));

                    b.Property<int>("CantidadBolsas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TurnoID")
                        .HasColumnType("int");

                    b.HasKey("LoteID");

                    b.HasIndex("FechaHoraFin");

                    b.HasIndex("FechaHoraInicio");

                    b.HasIndex("MaterialID");

                    b.HasIndex("NumeroLote")
                        .IsUnique();

                    b.HasIndex("TurnoID");

                    b.ToTable("LotesProduccion", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.LoteProveedorBolsa", b =>
                {
                    b.Property<int>("LoteProveedorBolsaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteProveedorBolsaID"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int");

                    b.Property<int>("CantidadDefectuosa")
                        .HasColumnType("int");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaRecepcion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProveedorBolsaID")
                        .HasColumnType("int");

                    b.Property<string>("TipoCemento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LoteProveedorBolsaID");

                    b.HasIndex("ProveedorBolsaID", "NumeroLote")
                        .IsUnique();

                    b.ToTable("LoteProveedorBolsa", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<decimal>("DensidadKGm3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DensildadKGm3");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("PesoBolsa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PesoPorBolsa");

                    b.HasKey("MaterialID");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Parada", b =>
                {
                    b.Property<int>("ParadaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParadaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParadaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Decripcion");

                    b.Property<int?>("DuracionMinutos")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHoraFin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHoraInicio");

                    b.Property<string>("TipoParada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int")
                        .HasColumnName("TurnoProduccionID");

                    b.HasKey("ParadaID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("Parada", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Personal", b =>
                {
                    b.Property<int>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalID");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.PersonalTurno", b =>
                {
                    b.Property<int>("PersonalTurnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalTurnoID"));

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("RolTurno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("PersonalTurnoID");

                    b.HasIndex("PersonalID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("PersonalTurno", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", b =>
                {
                    b.Property<int>("ProduccionMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduccionMaterialID"));

                    b.Property<int>("BolsasElaboradas")
                        .HasColumnType("int");

                    b.Property<int>("BolsasRotas")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasMarcha")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("ProduccionMaterialID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("ProduccionMaterial", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", b =>
                {
                    b.Property<int>("ProveedorBolsaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorBolsaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProveedorBolsaID");

                    b.ToTable("ProveedoresBolsa", (string)null);

                    b.HasData(
                        new
                        {
                            ProveedorBolsaID = 1,
                            Activo = true,
                            Descripcion = "Cooperativa de cemento",
                            Nombre = "Coselapa"
                        },
                        new
                        {
                            ProveedorBolsaID = 2,
                            Activo = true,
                            Descripcion = "Fabricante de bolsas",
                            Nombre = "Primo Tedesco"
                        },
                        new
                        {
                            ProveedorBolsaID = 3,
                            Activo = true,
                            Descripcion = "Bolsas para cemento",
                            Nombre = "Bolpar"
                        });
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.RegistroDefectoBolsa", b =>
                {
                    b.Property<int>("RegistroDefectoBolsaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegistroDefectoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroDefectoBolsaID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDefectuosa");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<int>("LoteProveedorBolsaID")
                        .HasColumnType("int")
                        .HasColumnName("LoteProveedorBolsaID");

                    b.Property<int?>("ProduccionMaterialID")
                        .HasColumnType("int")
                        .HasColumnName("ProduccionMaterialID");

                    b.Property<string>("TipoDefecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoDefecto");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int")
                        .HasColumnName("TurnoProduccionID");

                    b.HasKey("RegistroDefectoBolsaID");

                    b.HasIndex("LoteProveedorBolsaID");

                    b.HasIndex("ProduccionMaterialID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("RegistroDefectoBolsa", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.TurnoProduccion", b =>
                {
                    b.Property<int>("TurnoProduccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoProduccionID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TurnoNumero")
                        .HasColumnType("int");

                    b.HasKey("TurnoProduccionID");

                    b.HasIndex("Fecha", "TurnoNumero")
                        .IsUnique();

                    b.ToTable("TurnoProduccion", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("RolSistema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.HasIndex("PersonalID");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ConsumoBolsas", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", "ProduccionMaterial")
                        .WithMany("ConsumoBolsas")
                        .HasForeignKey("ProduccionMaterialID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", "ProveedorBolsa")
                        .WithMany("Consumos")
                        .HasForeignKey("ProveedorBolsaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "TurnoProduccion")
                        .WithMany("ConsumosBolsas")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProduccionMaterial");

                    b.Navigation("ProveedorBolsa");

                    b.Navigation("TurnoProduccion");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Despacho", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Material", null)
                        .WithMany("Despachos")
                        .HasForeignKey("MaterialID");

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.EventoCarga", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.LoteProduccion", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.LoteProveedorBolsa", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", "ProveedorBolsa")
                        .WithMany("Lotes")
                        .HasForeignKey("ProveedorBolsaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProveedorBolsa");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Parada", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Paradas")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.PersonalTurno", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Personal", "Personal")
                        .WithMany("Turnos")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("PersonalTurno")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Material", "Material")
                        .WithMany("Producciones")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Producciones")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.RegistroDefectoBolsa", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.LoteProveedorBolsa", "LoteProveedorBolsa")
                        .WithMany("Defectos")
                        .HasForeignKey("LoteProveedorBolsaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", "ProduccionMaterial")
                        .WithMany("DefectosBolsas")
                        .HasForeignKey("ProduccionMaterialID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "TurnoProduccion")
                        .WithMany("DefectosBolsas")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteProveedorBolsa");

                    b.Navigation("ProduccionMaterial");

                    b.Navigation("TurnoProduccion");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Personal", "Personal")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.LoteProveedorBolsa", b =>
                {
                    b.Navigation("Defectos");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Material", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Producciones");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Personal", b =>
                {
                    b.Navigation("Turnos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", b =>
                {
                    b.Navigation("ConsumoBolsas");

                    b.Navigation("DefectosBolsas");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.TurnoProduccion", b =>
                {
                    b.Navigation("ConsumosBolsas");

                    b.Navigation("DefectosBolsas");

                    b.Navigation("Paradas");

                    b.Navigation("PersonalTurno");

                    b.Navigation("Producciones");
                });
#pragma warning restore 612, 618
        }
    }
}
