// <auto-generated />
using System;
using CementoTrazabilidad.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CementoTrazabilidad.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128185503_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ConsumoBolsas", b =>
                {
                    b.Property<int>("ConsumoBolsasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumoBolsasID"));

                    b.Property<int>("CantidadBolsas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsumo")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoteBolsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorBolsaID")
                        .HasColumnType("int");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("ConsumoBolsasID");

                    b.HasIndex("ProveedorBolsaID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("ConsumoBolsas");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Despacho", b =>
                {
                    b.Property<int>("DespachoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespachoID"));

                    b.Property<int>("CantidadBolsas")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraDespacho")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteCamion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transportista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("DespachoID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PesoBolsa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Parada", b =>
                {
                    b.Property<int>("ParadaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParadaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonalResponsableID")
                        .HasColumnType("int");

                    b.Property<string>("TipoParada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("ParadaID");

                    b.HasIndex("PersonalResponsableID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Personal", b =>
                {
                    b.Property<int>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalID");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.PersonalTurno", b =>
                {
                    b.Property<int>("PersonalTurnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalTurnoID"));

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("RolTurno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("PersonalTurnoID");

                    b.HasIndex("PersonalID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("PersonalTurno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", b =>
                {
                    b.Property<int>("ProduccionMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduccionMaterialID"));

                    b.Property<int>("BolsasElaboradas")
                        .HasColumnType("int");

                    b.Property<int>("BolsasRotas")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasMarcha")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int>("TurnoProduccionID")
                        .HasColumnType("int");

                    b.HasKey("ProduccionMaterialID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("TurnoProduccionID");

                    b.ToTable("ProduccionMaterial");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", b =>
                {
                    b.Property<int>("ProveedorBolsaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorBolsaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorBolsaID");

                    b.ToTable("ProveedoresBolsa");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.TurnoProduccion", b =>
                {
                    b.Property<int>("TurnoProduccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoProduccionID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurnoNumero")
                        .HasColumnType("int");

                    b.HasKey("TurnoProduccionID");

                    b.HasIndex("Fecha", "TurnoNumero")
                        .IsUnique();

                    b.ToTable("TurnosProduccion");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("RolSistema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.HasIndex("PersonalID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ConsumoBolsas", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", "ProveedorBolsa")
                        .WithMany("ConsumosBolsas")
                        .HasForeignKey("ProveedorBolsaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "TurnoProduccion")
                        .WithMany()
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProveedorBolsa");

                    b.Navigation("TurnoProduccion");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Despacho", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Material", "Material")
                        .WithMany("Despachos")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Despachos")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Parada", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Personal", "PersonalResponsable")
                        .WithMany()
                        .HasForeignKey("PersonalResponsableID");

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Paradas")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalResponsable");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.PersonalTurno", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Personal", "Personal")
                        .WithMany("Turnos")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Personal")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProduccionMaterial", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Material", "Material")
                        .WithMany("Producciones")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CementoTrazabilidad.Core.Entidades.TurnoProduccion", "Turno")
                        .WithMany("Produccion")
                        .HasForeignKey("TurnoProduccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Usuario", b =>
                {
                    b.HasOne("CementoTrazabilidad.Core.Entidades.Personal", "Personal")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Material", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Producciones");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.Personal", b =>
                {
                    b.Navigation("Turnos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.ProveedorBolsa", b =>
                {
                    b.Navigation("ConsumosBolsas");
                });

            modelBuilder.Entity("CementoTrazabilidad.Core.Entidades.TurnoProduccion", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Paradas");

                    b.Navigation("Personal");

                    b.Navigation("Produccion");
                });
#pragma warning restore 612, 618
        }
    }
}
